import type { Metadata } from "next";
import { BRAND } from "@vidlore/core";
import { ProsePage } from "@/components/prose-page";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return (
    <ProsePage title="Terms of use" updated="October 2026">
      <p>
        {BRAND.name} is a free demo that turns a topic into a short AI-generated video. By using it you agree to these
        terms.
      </p>
      <h2>The demo</h2>
      <p>
        The service is provided as-is, for free, with daily usage limits. It may change, be unavailable, or remove stored
        videos at any time. Download any video you want to keep.
      </p>
      <h2>Your content</h2>
      <p>
        You own the videos you create and may use them for any lawful purpose, including commercially. You are
        responsible for your topics and scripts, and for making sure they don't infringe anyone's rights.
      </p>
      <h2>Acceptable use</h2>
      <p>
        Don't use {BRAND.name} to create content that is sexual, hateful, harassing, defamatory, dangerous, or that
        impersonates real people. Don't try to bypass the usage limits or overload the service. We may block topics and
        remove content that breaks these rules.
      </p>
      <h2>AI-generated content</h2>
      <p>
        Scripts, images and voices are generated by AI models and may contain mistakes. Check facts before you publish,
        and follow each platform's rules for labelling AI-generated content.
      </p>
      <h2>No warranty</h2>
      <p>
        To the extent permitted by law, the service is provided without warranties of any kind, and we are not liable for
        any loss arising from its use.
      </p>
    </ProsePage>
  );
}
